FROM pycon:base
MAINTAINER Jon Ferretti

RUN wget https://3230d63b5fc54e62148e-c95ac804525aac4b6dba79b00b39d1d3.ssl.cf1.rackcdn.com/Anaconda-2.2.0-Linux-x86_64.sh
RUN bash Anaconda-2.2.0-Linux-x86_64.sh -b
